### ISSUE TITLE
I cant drive it

### ISSUE THREAD

**Issue by nimaltd** [Lab409/driver_si4463#10]
Hello. I use stm32f103c8 and keil.
SI4463_Transmit()  , always return -50.
what is that problem ?

**Comment by DanilBorchevkin** [comment]
@nimaltd -50 means SI4463_ERR_OVER_TX_FIFO - overflow TX fifo

**Comment by nimaltd** [comment]
I know. But why ?

**Comment by DanilBorchevkin** [comment]
@nimaltd please post your routine with data sending so I could help you

**Comment by nimaltd** [comment]
/* StartDefaultTask function */
void StartDefaultTask(void const * argument)
{

  /* USER CODE BEGIN StartDefaultTask */
  /* Infinite loop */
	 /* Assign functions */

  si4463.IsClearToSend = SI4463_IsCTS;
  si4463.WriteRead = SI4463_WriteRead;
  si4463.Select = SI4463_Select;
  si4463.Deselect = SI4463_Deselect;
  si4463.SetShutdown = SI4463_SetShutdown;
  si4463.ClearShutdown = SI4463_ClearShutdown;
  si4463.DelayMs = SI4463_Delay;

  /* Disable interrupt pin for init Si4463 */
 HAL_NVIC_DisableIRQ(EXTI1_IRQn);

  /* Init Si4463 with structure */
  ii=SI4463_Init(&si4463);

  /* Clear RX FIFO before starting RX packets */
  SI4463_ClearRxFifo(&si4463);
  /* Start RX mode.
   * SI4463_StartRx() put a chip in non-armed mode in cases:
   * - successfully receive a packet;
   * - invoked RX_TIMEOUT;
   * - invalid receive.
   * For receiveing next packet you have to invoke SI4463_StartRx() again!*/
  SI4463_StartRx(&si4463, APP_PACKET_LEN, false, false, false);

#ifdef DEMOFEST
  /* Debug message on UART */
  printf("INIT\n");
#endif

  /* Enable interrupt pin and */
  HAL_NVIC_EnableIRQ(EXTI1_IRQn);
  /* Clear interrupts after enabling interrupt pin.
   * Without it may be situation when interrupt is asserted but pin not cleared.*/
  SI4463_ClearInterrupts(&si4463);
  for(;;)
  {
		sprintf((char*)outgoingBuffer,"%d",HAL_GetTick());
	  xx=SI4463_Transmit(&si4463, outgoingBuffer, APP_PACKET_LEN);
	  
    osDelay(50);
  }
  /* USER CODE END StartDefaultTask */
}

**Comment by nimaltd** [comment]
void GPIO_EXTI_Callback(void)
{
  /* Prevent unused argument(s) compilation warning */

	Last2=HAL_GetTick()-Last1;
	Last1=HAL_GetTick();
	

  /* Clear incoming buffer */
  memset(incomingBuffer, 0x00, APP_PACKET_LEN);

  /* Get interrupts and work with it */
  SI4463_GetInterrupts(&si4463);

  /* Handling PH interrupts */
  if (si4463.interrupts.filterMatch)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.filterMatch = false;
  }
  if (si4463.interrupts.filterMiss)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.filterMiss = false;
  }
  if (si4463.interrupts.packetSent)
  {
	  /* Handling this interrupt here */
	  /* Clear TX FIFO */
	  SI4463_ClearTxFifo(&si4463);
#ifdef DEMOFEST
	  printf("OUT >");
		for(uint8_t i=0;i<APP_PACKET_LEN;i++)
			printf("%c",outgoingBuffer[i]);
	  printf("\n");
#endif /* DEMOFEST */
	  /* Re-arm StartRX */
	  SI4463_StartRx(&si4463, APP_PACKET_LEN, false, false, false);

	  /*Toggle led for indication*/
	  //HAL_GPIO_TogglePin(LED_ONBOARD_GPIO_Port, LED_ONBOARD_Pin);
		LL_GPIO_TogglePin(LED_ONBOARD_GPIO_Port,LED_ONBOARD_Pin);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.packetSent = false;
  }
  if (si4463.interrupts.packetRx)
  {
	  /* Handling this interrupt here */
	  /* Get FIFO data */
	  SI4463_ReadRxFifo(&si4463, incomingBuffer, APP_PACKET_LEN);
	  /* Clear RX FIFO */
	  SI4463_ClearRxFifo(&si4463);
#ifdef DEMOFEST
	  printf("IN >");
		for(uint8_t i=0;i<APP_PACKET_LEN;i++)
			printf("%c",incomingBuffer[i]);
	  printf("\n");
#endif /* DEMOFEST */

	  /* Start RX again.
	   * It need because after successful receive a packet the chip change
	   * state to READY.
	   * There is re-armed mode for StartRx but it not correctly working */
	  SI4463_StartRx(&si4463, APP_PACKET_LEN, false, false, false);

	  /*Toggle led for indication*/
	  LL_GPIO_TogglePin(LED_ONBOARD_GPIO_Port, LED_ONBOARD_Pin);

	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.packetRx = false;
  }
  if (si4463.interrupts.crcError)
  {
	  /* Handling this interrupt here */

	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.crcError = false;
  }
  if (si4463.interrupts.txFifoAlmostEmpty)
  {
	  /* Handling this interrupt here */

	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.txFifoAlmostEmpty = false;
  }
  if (si4463.interrupts.rxFifoAlmostFull)
  {
	  /* Handling this interrupt here */

	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.rxFifoAlmostFull = false;
  }

  /* Handling Modem interrupts */
  if (si4463.interrupts.postambleDetect)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.postambleDetect = false;
  }
  if (si4463.interrupts.invalidSync)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.invalidSync = false;
  }
  if (si4463.interrupts.rssiJump)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.rssiJump = false;
  }
  if (si4463.interrupts.rssi)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.rssi = false;
  }
  if (si4463.interrupts.invalidPreamble)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.invalidPreamble = false;
  }
  if (si4463.interrupts.preambleDetect)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.preambleDetect = false;
  }
  if (si4463.interrupts.syncDetect)
  {
	  /* Handling this interrupt here */
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.syncDetect = false;
  }

  /* Handling Chip interrupts */
  if (si4463.interrupts.cal)
  {
	  /* Handling this interrupt here */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.cal = false;
  }
  if (si4463.interrupts.fifoUnderflowOverflowError)
  {
	  /* Handling this interrupt here */
	  /* Clear RX FIFO */
	  SI4463_ClearRxFifo(&si4463);
	  /* Claer Chip Status errors if exists */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.fifoUnderflowOverflowError = false;
  }
  if (si4463.interrupts.stateChange)
  {
	  /* Handling this interrupt here */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.stateChange = false;
  }
  if (si4463.interrupts.cmdError)
  {
	  /* Handling this interrupt here */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.stateChange = false;
  }
  if (si4463.interrupts.chipReady)
  {
	  /* Handling this interrupt here */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.chipReady = false;
  }
  if (si4463.interrupts.lowBatt)
  {
	  /* Handling this interrupt here */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.lowBatt = false;
  }
  if (si4463.interrupts.wut)
  {
	  /* Handling this interrupt here */
	  SI4463_GetChipStatus(&si4463);
	  /* Following instruction only for add breakpoints. May be deleted */
	  si4463.interrupts.wut = false;
  }

  /* Clear All interrupts before exit */
  SI4463_ClearAllInterrupts(&si4463);
}


bool SI4463_IsCTS(void)
{
	if(HAL_GPIO_ReadPin(CTS_GPIO_Port, CTS_Pin) == GPIO_PIN_SET)
	{
		return true;
	}
	else
	{
		return false;
	}
}

void SI4463_WriteRead(const uint8_t * pTxData, uint8_t * pRxData, const uint16_t sizeTxData)
{
	HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)pTxData, pRxData, sizeTxData, 100);
}

void SI4463_SetShutdown(void)
{
	HAL_GPIO_WritePin(SD_GPIO_Port, SD_Pin, GPIO_PIN_SET);
		for(uint8_t	i=0;i<10;i++)
		__NOP();

}

void SI4463_ClearShutdown(void)
{
	HAL_GPIO_WritePin(SD_GPIO_Port, SD_Pin, GPIO_PIN_RESET);
		for(uint8_t	i=0;i<10;i++)
		__NOP();

}

void SI4463_Select(void)
{
	HAL_GPIO_WritePin(CS_GPIO_Port, CS_Pin, GPIO_PIN_RESET);
	for(uint8_t	i=0;i<10;i++)
		__NOP();

}

void SI4463_Deselect(void)
{
	__NOP();__NOP();__NOP();__NOP();__NOP();
	HAL_GPIO_WritePin(CS_GPIO_Port, CS_Pin, GPIO_PIN_SET);
	for(uint8_t	i=0;i<10;i++)
		__NOP();

}

void SI4463_Delay(uint32_t d)
{
	osDelay(d);
}

**Comment by DanilBorchevkin** [comment]
How length of the packet do you use?

сб, 7 апр. 2018 г., 9:48 Nima Askari ----- نیما عسکری <
notifications@github.com>:

**Comment by nimaltd** [comment]
Your default config. I think 10

**Comment by DanilBorchevkin** [comment]
@nimaltd please check the value of the APP_PACKET_LEN. It literal should be created in your app

**Comment by nimaltd** [comment]
I dont have si4463 Know :(
