### ISSUE TITLE
Function in si4463_t struct

### ISSUE THREAD

**Issue by nazmibojan** [Lab409/driver_si4463#11]
Hi All,

Very nice project, but I couldn't found this function (in si4463.h) in any .c file inside this project

typedef struct
{
        void (*WriteRead)(const uint8_t * pTxData, uint8_t * pRxData, const uint16_t txSize);
	void (*SetShutdown)(void);
	void (*ClearShutdown)(void);
	void (*Select)(void);
	void (*Deselect)(void);
	void (*DelayMs)(uint32_t delayMs);
	uint8_t (*IsClearToSend)(void);
	si4463_interrupts_t interrupts;
	si4463_chip_status_t chipStatus;
} si4463_t;

Where can I Find this function?

Thanks,
Nazmi

**Comment by olegantonyan** [comment]
You have to implement these functions for your particular hardware. Check out examples https://github.com/Lab409/example_si4463

**Comment by nazmibojan** [comment]
Great. Thanks Oleg!
