### ISSUE TITLE
Дилэй не нужен

### ISSUE THREAD

**Issue by olegantonyan** [Lab409/driver_si4463#5]
Судя по моим изысканиям задержки вообще не нужны. Из-за них были странности: 1 из 5 раз инициализация не проходила, зависоны в процессе работы, зависон при инициализации при включенной калибровке АЦП - дичь короче. Методом shotgun programming понизил частоту SPI в 2 раза и убрал задержки вообще (функцию пустышку передаю). Глюки прекратились. Причём частота SPI похоже не влияет. Вангую что проблемы могли быть из-за подключенного отладчика

Возможно стоит упомянуть это в errata

**Comment by DanilBorchevkin** [comment]
Принял.

Проблема в том, что модулей то у меня нет и проверить не могу. Подумаю, что с этим можно сделать.

**Comment by DanilBorchevkin** [comment]
@olegantonyan не подтверждено.

Если убрать в **_SI4463_Init()_** задержку после передачи каждой команды, это будет приводить к ошибке:
1. Вызывается прерывание **_cmdError_**
2. При получение данных при помощи **GET_CHIP_STATUS**  показывает ошибку "18" - из документации это "_Command was issued before previous command was completed._"

При возврате задержки ошибка более не вызывается
